### ISSUE TITLE
upward_rank is not pure

### ISSUE THREAD

**Issue by stsievert** [myxie/shadow#20]
The function [upward_rank][u] is not pure: it modifies the input data, a "side effect" in functional-programming lingo. Pure functions are easier to reason about, combine, test, debug and parallelize ([source][3]). This is motivation for Dask assumes functions are pure by default ([docs][1]) and "side effects are rarely used [in functional programming]" ([wiki][2]). 

[u]:https://github.com/myxie/shadow/blob/164ae9884363b9ac92eea1e3b437c721568849d4/shadow/algorithms/heuristic.py#L176
[1]:https://distributed.dask.org/en/latest/client.html#pure-functions-by-default
[2]:https://en.wikipedia.org/wiki/Side_effect_(computer_science)
[3]:https://blog.knoldus.com/scala-best-practices-pure-functions/

**Comment by stsievert** [comment]
This issue could be resolved with these implementations:

1. Modify a copy of the input in `upward_rank`
2. Move `upward_rank` as a method of the workflow class.

Option 1 would look something like this if the NumPy API is followed:

``` python
from copy import copy, deepcopy

def upward_rank(workflow, out=None):
    if out is None:
        out = copy(workflow)
    # ... rest of upward_rank
    return out
```

Option 2 would amount to deprecating `shadow.algorithms.heuristic.upward_rank` and moving it to `shadow.models.workflow.Workflow`.

**Comment by myxie** [comment]
This is something I have been unhappy with for a while, but have not been able to put a name on it (thank you for the example of 'pure and non-pure functions'). There is a lot of C-style variable manipulation going on in the code base, where data is passed to a function and that data is what is manipulated, rather than returning the data. This is my past as C developer showing...

I am hesitant to add `upward_rank` as a method for the `Workflow` class, because it is not intrinsic to the concept of a workflow - rather, one of many ranking methods for tasks in a workflow.

One alternative I have been toying withsince you mentioned it in the [SciPy Proceedings pull request](https://github.com/scipy-conference/scipy_proceedings/pull/553#discussion_r438458254) is making Heuristic a class, i.e.


``` python


class Heuristic:
    def __init__(self, workflow):
   self.workflow = workflow


   def heft():
       self._upward_rank()
```

I can see the benefit of this approach being easier for people to develop their own heuristics by simply using `Heuristic` as a base class that they can build their own `MyPersonalHeuristicClass` from, in addition to being more purely OOP. 

I will start a new branch over the weekend and see where I get to with it. Thanks again for raising this issue!

**Comment by myxie** [comment]
This has been updated in https://github.com/myxie/shadow/commit/cb6143ae98b5c30fc171d4b9572bff0506637806. 

For example, the `heft` function now looks something like: 

``` python
...
	task_ranks = calculate_upward_ranks(workflow)
	for task in workflow.tasks:
		task.rank = task_ranks[task]
	solution = insertion_policy(workflow)
```
A `Solution` object is also generated within in the insertion_policy() function, rather than using the `Solution` from the Workflow object (`Workflow` objects will soon cease to have `Solution` objects as attributes).

**Comment by stsievert** [comment]
:+1: Thanks for the resolution! should this issue be closed?
